language: android
android:
  components:
    - tools
    - build-tools-23.0.2
    - android-23
    - extra-android-m2repository
    - extra-android-support

before_install:
 - chmod +x gradlew  # 改变gradlew的访问权限

script:
  ./gradlew assembleRelease

before_install:
  - gem install fir-cli
after_deploy:
  - fir p app/build/outputs/apk/app-release.apk -T 574df8872a3f7fe0fb8a63282eecd619 -c "`git cat-file tag $TRAVIS_TAG`"