language: android

android:
  components:
    - tools
    - build-tools-24.0.1
    - android-24
    - extra-android-m2repository

jdk: oraclejdk8


sudo: false

cache:
  directories:
    - $HOME/.gradle

before_install:
 - chmod +x gradlew

script:
    - ./gradlew assembleRelease

deploy:
      provider: releases
      file: app/build/outputs/apk/app-release.apk
      skip_cleanup: true
      on:
        tags: true
        all_branches: true


